export const ADD_TO_CART ="ADD_TO_CART";
export const ADD_TO_CART_MENU ="ADD_TO_CART_MENU";
export const ADD_TO_CART_PIZZA ="ADD_TO_CART_PIZZA";
export const REMOVE_ONE_FORM_CART = "REMOVE_ONE_FROM_CART";
export const REMOVE_ALL_FROM_CART = "REMOVE_ALL_FROM_CART";
export const CLEAR_CART = "CLEAR_CART";